### ISSUE TITLE
Add hotel rooms amenities

### ISSUE THREAD

**Issue by AugustoL** [windingtree/crypto-booking#144]
Show amenities for each room type in the app, they can be accessed from /HOTEL_ADDRESS/roomTypes.

i32 hotel roomTypes example: https://demo-api.windingtree.com/hotels/0x4Ee2BC4804D1A75AEBa5C76D25cc2c036B136140/roomTypes

**Comment by PabloAlice** [comment]
@skkr you will find the amenities in the Room props, like, props.room.amenities.
