### ISSUE TITLE
Update text content and style in hotel rooms section

### ISSUE THREAD

**Issue by skkr** [windingtree/crypto-booking#203]
Update text about hotel and rooms:

- some strange quotes used like **
- reduce text about hotel in 2-3 times (@menschikov we need the content)

Once the text is changed:
- Make font larger

**Comment by skkr** [comment]
@menschikov as mentioned, we need the shorter version of the text
@MatiasOS once the new content is set, let me know and I'll make the style changes

**Comment by AugustoL** [comment]
@skkr the test is in markdown format, that means that the content between ** should be in bold, like **PURE COZY**

You can use this lib to parse markdown to html https://www.npmjs.com/package/markdown

**Comment by skkr** [comment]
Thanks @AugustoL 👍 

https://github.com/windingtree/crypto-booking/pull/266

Still pending to replace the text, when the new one is provided we can enlarge the font size.

**Comment by skkr** [comment]
@MatiasOS this is the new text, let me know when is updated to make the restyling.

**Boutique Hotel i31 Berlin** – The 4 star superior hotel located in the heart of Berlin welcomes ETH Berlin guests with a modern design harmonized with Berlin’s relaxed lifestyle. We offer our guests elegant, contemporary style rooms with individual design and high-quality interior.

**Comment by JirkaChadima** [comment]
@skkr I've shortened the hotel description in the live data

**Comment by skkr** [comment]
@JirkaChadima , thanks!
