### ISSUE TITLE
Avoid calculate the final price if the date is invalid

### ISSUE THREAD

**Issue by beogip** [windingtree/crypto-booking#212]
<img width="729" alt="screen shot 2018-08-04 at 12 15 48 pm" src="https://user-images.githubusercontent.com/1965274/43677906-36ccca48-97e0-11e8-82e9-0dadf1bc8fca.png">

**Comment by AugustoL** [comment]
@beogip if we will display number of nighst this wont be an issue anymore, right?

**Comment by AugustoL** [comment]
Closing since we dont display calendar anymore
