### ISSUE TITLE
Send rigth TX instructions for Lif 

### ISSUE THREAD

**Issue by AugustoL** [windingtree/crypto-booking#249]
@skkr The email that the guests receive with instructions for lif contains only one tx and it should show any value since the value is 0 for both txs it needs to send.

It should be smth like this:

Payment instructions
--
In order to pay for your room, please send this transaction in order.

To: tx[0].to
Data: tx[0].data

To: tx[1].to
Data: tx[1].data

**Comment by skkr** [comment]
From @MatiasOS 
>Please use a loop on the array txs or an if to avoid tx[1] if not exists.
>Because the instructions are used for eth and Lif, thus some times there is only one and other times are two

**Comment by MatiasOS** [comment]
Closed in #259
