### ISSUE TITLE
Reservation Date

### ISSUE THREAD

**Issue by MatiasOS** [windingtree/crypto-booking#270]
Reservation date is not displaying correctly in mobile.

![photo_2018-08-07_20-07-53](https://user-images.githubusercontent.com/5481398/43791496-8101a37c-9a7e-11e8-9a20-3cb80814e0ee.jpg)

**Comment by skkr** [comment]
Let's change this like it is on the wireframes.

![image](https://user-images.githubusercontent.com/1435069/43795591-354c40de-9a58-11e8-85fd-16965dd71085.png)

**Comment by AugustoL** [comment]
@skkr can we have this done today?
