### ISSUE TITLE
Application loader animation on slow connections

### ISSUE THREAD

**Issue by martinbilek** [windingtree/crypto-booking#284]
When I open application on slow connection, it takes some time to see some content. It should be nice to see some loading animation like http://tobiasahlin.com/spinkit/. Maybe we have some WT logo animation in pure CSS?

Now it looks like this on slow connection (GSM/3G):

![s1](https://user-images.githubusercontent.com/797392/43899485-627c9320-9be2-11e8-9422-23a1f0a0e1a5.gif)

**Comment by skkr** [comment]
By now let's use the loading animation we have (the spinner), the plan is to make something much better and include it in the WT-CSS framework. After other issues are resolved we can continue with this if necessary.
