### ISSUE TITLE
Collapsed menu won't appear after click on small screen

### ISSUE THREAD

**Issue by martinbilek** [windingtree/crypto-booking#288]
When I touch menu button nothing will happen.

![screen shot 2018-08-09 at 16 08 50](https://user-images.githubusercontent.com/797392/43904775-d4e4f9a4-9bef-11e8-9689-e85e74dda44c.png)

**Comment by skkr** [comment]
This seems to be working well now. @AugustoL , @MatiasOS can you confirm if so?

**Comment by AugustoL** [comment]
Works for me, closing it
