### ISSUE TITLE
Add from/to dates in .env

### ISSUE THREAD

**Issue by beogip** [windingtree/crypto-booking#355]
We need to add from/to dates in the .env. Also, it's necessary to adapt the front end to calculate the reservation date using that information
ie:
``` bash
fromDate = 06/09/2018
toDate = 10/09/2018
```
<img width="438" alt="screen shot 2018-08-28 at 8 06 01 am" src="https://user-images.githubusercontent.com/1965274/44719302-40e0e980-aa99-11e8-8857-a4a353a82629.png">

**Comment by beogip** [comment]
@MatiasOS I'll take this issue.

**Comment by MatiasOS** [comment]
I have created `INITIAL_DATE` and `FINAL_DATE` but is used only in server side.
