### ISSUE TITLE
Store dates instead of month days

### ISSUE THREAD

**Issue by beogip** [windingtree/crypto-booking#356]
Currently, we are storing in the DB two props: `from` (0 < from < 5) and `to` (from <= to < 5). We should store actual dates, validate it with the .env variables that were created in #355 and make the property conversion to send it to the smart contract.

**NOTE: this issue it's blocked by #355**

**Comment by MatiasOS** [comment]
I have created `INITIAL_DATE` and `FINAL_DATE` for the server.

**Comment by MatiasOS** [comment]
Closed by #397
