### ISSUE TITLE
Preferred room type

### ISSUE THREAD

**Issue by czervenka** [windingtree/crypto-booking#361]
There is selection of room type in the form.

- It seems to me that there should be "Pure Cozy" and "White & Brown Comfort" for selection not "twin bed" and "king bed".
- "Preferred room type" could be hard to understand for non-technical users. Let's use more common label "Select room" or just "Room" as label.

**Comment by skkr** [comment]
@czervenka, first point was a suggestion from Dave. It was like that before, but he pointed out that from an user perspective is best to know what type of room they will get, rather than the name of the room.

**Comment by czervenka** [comment]
@skkr thanks for quick replay. It make sense but then it is inconsistent. User reads description of room, lists amenities and examines images, click book the room. And suddenly there is no room name in the booking form. So how do he/she knows what room is he/she paying for? We should express the bed type in the room description as well or add room name to the form IMO.

Anyway the bed type selected by clicking on "Boot this room" does not correspond to bed type in description. Pure cozy has Kind bed in description but Twin is selected and contrary for White & Brown.

**Comment by skkr** [comment]
Got it. Just made Alex aware of this.

**Comment by menschikov** [comment]
Guys, there should be same name for the card of room and selector item in the booking form. I suggest use common names like "Twin Bed Room" and "King-size Bed Room" (or Standard Room and Comfort room). This is what simple, common and people can remember easily.

**Comment by skkr** [comment]
Right, I'll make the change in the frontend. 

@MatiasOS can you change the room names so we get the right data?

**Comment by MatiasOS** [comment]
Can we just change the text in app? 
We are using room type as index at blockchain level. A real rename across the app will cost us a lot of work and time.

**Comment by AugustoL** [comment]
We cant change the room types names in the smart contract level, I would recommend to just change the text in the app or have a room type name for each room type id and use that.

**Comment by skkr** [comment]
Thanks guys, I'll change the text in the app.
