### ISSUE TITLE
Booking form - reservation date

### ISSUE THREAD

**Issue by czervenka** [windingtree/crypto-booking#362]
The reservation date input widget seems unpredictable for the first time as I never know what happens when I click a number. The simple solution would be to replace it with two combo boxes: `arrival [6.9.] - departure [8.9.]` which IMO would work the best. The other option I - think of - is a touch and drug ... touch to select one date and drug to any direction to select more days.

**Comment by menschikov** [comment]
![image](https://user-images.githubusercontent.com/4557491/44859636-faa0ab80-ac8d-11e8-82d3-a9bf29291292.png)
guys, are we in july?

**Comment by AugustoL** [comment]
@menschikov not anymore
