### ISSUE TITLE
Cancellation policy is unclear

### ISSUE THREAD

**Issue by czervenka** [windingtree/crypto-booking#380]
The policy is:
> Please note the cancellation policy before committing to a reservation.
>
> Booking canceled a week before: 50% refund.
> Booking canceled a day before: 25% refund.
> Booking canceled in the last 24 hours: 10% refund.

What does that mean? If I cancel the booking month before the event will I be 100% refunded or just 50%? Booking canceled a day before is the same as 24 hours before, isn't it?

Shouldn't it be something like:

> Any cancellation more than a 7 days prior to checkin date will be refunded by 50% of the price of booking.
> Any cancellation between a 7 and 1 day before checking date will be refunded by 25% of the price of booking.
> Any cancellation less than 1 day before checking will be refunded by 10% of the price of booking.
> Cancellation past the booking time is not possible.

**Comment by MatiasOS** [comment]
Yes, it is unclear. I like the text that you proposes. I think this will be good as first issue
